using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class MoveController : MonoBehaviour

{
    private Animator animator;
    // Start is called before the first frame update
    void Start()  {
        animator = GetComponent<Animator>();
    }
    // Update is called once per frame
    void Update()  {
        if (Input.GetKey(KeyCode.UpArrow) || Input.GetKey(KeyCode.W))   {
            animator.SetBool("Walk", true);
            transform.position += transform.forward * 0.01f;
        } else {
            animator.SetBool("Walk", false);
        }

        if (Input.GetKey(KeyCode.DownArrow) || Input.GetKey(KeyCode.S))  {
            animator.SetBool("Back", true);
            transform.position -= transform.forward * 0.01f;
        }  else  {
            animator.SetBool("Back", false);
        }

        if (Input.GetKey(KeyCode.RightArrow) || Input.GetKey(KeyCode.D))   {
            transform.Rotate(0.0f, 1.0f, 0.0f);
        }
        if (Input.GetKey(KeyCode.LeftArrow) || Input.GetKey(KeyCode.A))   {
            transform.Rotate(0.0f, -1.0f, 0.0f);
        }
    }
}
